// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZML1xuTN97r7Hq3oLv_gYdXRzCyCI7tk',
    appId: '1:432500434219:web:fe7fb7c06d1a002186916e',
    messagingSenderId: '432500434219',
    projectId: 'tfg-millan-ac682',
    authDomain: 'tfg-millan-ac682.firebaseapp.com',
    storageBucket: 'tfg-millan-ac682.appspot.com',
    measurementId: 'G-S9M70E4M0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqTMApDQxU424hcXmucRwi47T3d92UTV4',
    appId: '1:432500434219:android:5bbf3a9230d6e91586916e',
    messagingSenderId: '432500434219',
    projectId: 'tfg-millan-ac682',
    storageBucket: 'tfg-millan-ac682.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvFNZE1MOKow9ZfC0dtLuI7I569Fq4oNU',
    appId: '1:432500434219:ios:6c818c8c065ded1e86916e',
    messagingSenderId: '432500434219',
    projectId: 'tfg-millan-ac682',
    storageBucket: 'tfg-millan-ac682.appspot.com',
    iosBundleId: 'com.example.tfg',
  );
}
